### ISSUE TITLE
Opinion de la comunidad sobre pago del evento

### ISSUE THREAD

**Issue by cloudnativecostarica** [cloudnativecostarica/kcd-planning-2025#2]
Enviar un email con un formulario a los asistentes del KCD 2024 para conocer su opinión si pagarían un ticket entre 10-20 dolares americanos.

**Comment by falconcr** [comment]
Formulario enviado https://forms.gle/7rnS3qrKy7kGRBEm8
Podriamos darle un par de dias para evaluar los resultados.
